[package]
name = "audio-classifier"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
ndarray = "0.15.6"
ndarray-stats = "0.5.1"
numpy = "0.17.2"
once_cell = "1.16.0"
serde = "1.0.147"
serde-pickle = "1.1.1"

[dependencies.pyo3]
version = "0.17.3"
features = ["auto-initialize"]
